network:
  version: 2
  ethernets:
    eth1:
      addresses: [192.168.20.2/24]
      routes:
        - to: default
          via: 192.168.20.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]