network:
  version: 2
  ethernets:
    enp0s3:
      addresses:
        - 192.168.20.60/24
        - 2001:db8:20::60/64
      routes:
        - to: default
          via: 192.168.20.1
        - to: default
          via: 2001:db8:20::1
      nameservers:
        addresses: [192.168.20.20, 2001:db8:20::20]
        search: [gponlab.local]
