network:
  version: 2
  ethernets:
    enp0s3:
      addresses:
        - 192.168.50.10/25
        # - 2001:db8:50::10/64
      routes:
        - to: default
          via: 192.168.50.1
      nameservers:
        addresses: [192.168.20.20, 1.1.1.1]
        search: [gponlab.local]
